//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DmClient.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetDHSoapBinding", Namespace="http://www.sample-package.org")]
    public partial class GetDH : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCollarsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAssaysOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetDH() {
            this.Url = global::DmClient.Properties.Settings.Default.DmClient_localhost_GetDH;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCollarsCompletedEventHandler GetCollarsCompleted;
        
        /// <remarks/>
        public event GetAssaysCompletedEventHandler GetAssaysCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sample-package.org#GetDH:GetCollars", RequestNamespace="http://www.sample-package.org", ResponseNamespace="http://www.sample-package.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Collars", IsNullable=false)]
        public Collar[] GetCollars() {
            object[] results = this.Invoke("GetCollars", new object[0]);
            return ((Collar[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCollarsAsync() {
            this.GetCollarsAsync(null);
        }
        
        /// <remarks/>
        public void GetCollarsAsync(object userState) {
            if ((this.GetCollarsOperationCompleted == null)) {
                this.GetCollarsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCollarsOperationCompleted);
            }
            this.InvokeAsync("GetCollars", new object[0], this.GetCollarsOperationCompleted, userState);
        }
        
        private void OnGetCollarsOperationCompleted(object arg) {
            if ((this.GetCollarsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCollarsCompleted(this, new GetCollarsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sample-package.org#GetDH:GetAssays", RequestNamespace="http://www.sample-package.org", ResponseNamespace="http://www.sample-package.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Assays", IsNullable=false)]
        public Assay[] GetAssays() {
            object[] results = this.Invoke("GetAssays", new object[0]);
            return ((Assay[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAssaysAsync() {
            this.GetAssaysAsync(null);
        }
        
        /// <remarks/>
        public void GetAssaysAsync(object userState) {
            if ((this.GetAssaysOperationCompleted == null)) {
                this.GetAssaysOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAssaysOperationCompleted);
            }
            this.InvokeAsync("GetAssays", new object[0], this.GetAssaysOperationCompleted, userState);
        }
        
        private void OnGetAssaysOperationCompleted(object arg) {
            if ((this.GetAssaysCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAssaysCompleted(this, new GetAssaysCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sample-package.org/DrillHole")]
    public partial class Collar {
        
        private string bHIDField;
        
        private int benchField;
        
        private string blastField;
        
        private int holeField;
        
        private decimal xCollarField;
        
        private decimal yCollarField;
        
        private decimal zCollarField;
        
        private decimal depthField;
        
        private string drillerField;
        
        /// <remarks/>
        public string BHID {
            get {
                return this.bHIDField;
            }
            set {
                this.bHIDField = value;
            }
        }
        
        /// <remarks/>
        public int Bench {
            get {
                return this.benchField;
            }
            set {
                this.benchField = value;
            }
        }
        
        /// <remarks/>
        public string Blast {
            get {
                return this.blastField;
            }
            set {
                this.blastField = value;
            }
        }
        
        /// <remarks/>
        public int Hole {
            get {
                return this.holeField;
            }
            set {
                this.holeField = value;
            }
        }
        
        /// <remarks/>
        public decimal XCollar {
            get {
                return this.xCollarField;
            }
            set {
                this.xCollarField = value;
            }
        }
        
        /// <remarks/>
        public decimal YCollar {
            get {
                return this.yCollarField;
            }
            set {
                this.yCollarField = value;
            }
        }
        
        /// <remarks/>
        public decimal ZCollar {
            get {
                return this.zCollarField;
            }
            set {
                this.zCollarField = value;
            }
        }
        
        /// <remarks/>
        public decimal Depth {
            get {
                return this.depthField;
            }
            set {
                this.depthField = value;
            }
        }
        
        /// <remarks/>
        public string Driller {
            get {
                return this.drillerField;
            }
            set {
                this.drillerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sample-package.org/DrillHole")]
    public partial class Assay {
        
        private string bHIDField;
        
        private string sampleField;
        
        private decimal fromField;
        
        private decimal toField;
        
        private decimal lengthField;
        
        private decimal vesField;
        
        private decimal gC_AuField;
        
        private string blankField;
        
        /// <remarks/>
        public string BHID {
            get {
                return this.bHIDField;
            }
            set {
                this.bHIDField = value;
            }
        }
        
        /// <remarks/>
        public string Sample {
            get {
                return this.sampleField;
            }
            set {
                this.sampleField = value;
            }
        }
        
        /// <remarks/>
        public decimal From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public decimal To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public decimal Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public decimal Ves {
            get {
                return this.vesField;
            }
            set {
                this.vesField = value;
            }
        }
        
        /// <remarks/>
        public decimal GC_Au {
            get {
                return this.gC_AuField;
            }
            set {
                this.gC_AuField = value;
            }
        }
        
        /// <remarks/>
        public string Blank {
            get {
                return this.blankField;
            }
            set {
                this.blankField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetCollarsCompletedEventHandler(object sender, GetCollarsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCollarsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCollarsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Collar[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Collar[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetAssaysCompletedEventHandler(object sender, GetAssaysCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAssaysCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAssaysCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Assay[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Assay[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591